### ISSUE TITLE
can't close notifications

### ISSUE THREAD

**Issue by xdaniel2063** [tfrommen/Dobby#9]
Hello,

me again. I mentioned on several installation that I can't close some notification when Dobby is activated. For example like the one attached.

When I disable Dobby I can close them.

Best wishes

Daniel

<img width="990" alt="2017-08-29 20_18_58-plugins celtic-rock de wordpress" src="https://user-images.githubusercontent.com/4562987/29837302-0b4eb438-8cf8-11e7-9bb1-a8b11365cd3a.png">

**Comment by tfrommen** [comment]
Hi Daniel,

I'm pretty confident this is due to event listeners having been added to specific elements (e.g., via their ID), instead of adding them, for example, to the `body` element and then use delegation.

Unfortunately, I don't have the time to look into this before next week.
I hope I can get around the issue by not moving the captured elements in the DOM, but actually wrapping them in Dobby's _closet_ directly, meaning rendering the opening and closing tags separately as first and last things in the admin notice area...

I'll keep you up to date.

**Comment by tfrommen** [comment]
Hi Daniel,

I finally had some time to dig into this. Can you please check if the new branch, [`issue_9`](https://github.com/tfrommen/Dobby/compare/issue-9), is working for you?

The branch already contains a dismissible _ERROR!_ notice for testing purposes, but please also test this with the notice(s) you had problems with before.

Thanks a lot in advance,
Thorsten

**Comment by xdaniel2063** [comment]
Hello Thorsten,

at the moment there are no more of these messages, but I'll have a look on it the next days and come back. Thanks for your work.

Best, Daniel

**Comment by xdaniel2063** [comment]
Hello Thorsten, tested it on a different installation and comet cache messages. Closing them worked fine now. Best, Daniel

**Comment by tfrommen** [comment]
Great! Thanks for reporting back.

I'll release a new version later today, or tomorrow.

**Comment by tfrommen** [comment]
Fixed in d0edcd52ff0a4ce11da719c0426c4e5e72fb1b2c.
